#undef RBPC
#undef RMAP_
#undef RMAP_PC
#undef RB
#undef RL
#undef RW
#undef REGI_SP
#undef REG_SP
#undef REG_
#undef REG_A
#undef WB
#undef WW
#undef WL
#undef W_
#undef R_
#undef WL_
#undef WW_
#undef RL_
#undef RW_
#undef RWPC
#undef N_BIT
#undef C_BIT
#undef Z_BIT
#undef V_BIT
#undef S_BIT
#undef M_BIT
#undef PRE_SF
#undef AFT_SF
#undef RLPC

#undef ROM_
#undef ROM_W
#undef ROM_R

#undef M_ROM
#undef M_RAM

#undef MI_ROM
#undef MI_RAM
#undef MI_VRAM

#undef RAM_
#undef RAM_W
#undef RAM_R

#undef STATUSFLAGS

#undef RMAP_IO
#undef WIO
#undef RIO
#undef ISIO